spring:
  docker:
    compose:
      file: walletApp/docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5434/walletdata
    username: postgres
    password: 7890123456Upet
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5434/walletdata
    user: postgres
    password: 7890123456Upet
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/db.changelog/db.changelog-master.yml